# Site settings
title: "Lukas Normantas"
description: "Single page resume for Lukas Normantas who is a soon-to-be Computer Science graduate"
keywords: "resume, résumé, cv, curriculum vitae, lukas normantas, recruitment, software engineer, technology, job, hiring"
robots: "index, follow"
author: "Lukas Normantas"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  true
resume_name:                    "Lukas Normantas"
resume_title:                   "Computer Science, Final Year Student"
resume_contact_email:           "me@lukasn.com"
resume_contact_telephone:       "07397300540"
# resume_header_quote:          "" If I ever come up with an amazing quote
resume_header_intro:            "<p>Hello! I'm quick to adapt to new technologies, motivated about ambitious projects and love to try new things. I have worked as a Software Engineer previously and have now secured a role as a System Architect following my graduation.</p>"

resume_looking_for_work:        false
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
resume_social_links:
  resume_website_url:           "https://lukasn.com/" # a little useless because they're currently on this page
  resume_github_url:            "https://github.com/xylust"
  resume_linkedin_url:          "https://www.linkedin.com/in/lukinskas/"
  # resume_twitter_url:           "" I'm not active on Twitter
  # resume_dribbble_url:          "" I'm not a web designer
  # resume_facebook_url:          "" I'd prefer an e-mail as opposed to somebody friend requesting me
  # resume_instagram_url:         "" Selfies and food pictures won't help land a job
resume_print_social_links:      true

# Design settings
resume_theme:                   default
